// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD36ntBS4oSH5TsvhQHbPuv1ocCpjMaPSs',
    appId: '1:198400828838:web:0fbe5dfc48291e4b995b67',
    messagingSenderId: '198400828838',
    projectId: 'healthnutritionmonitoringapp',
    authDomain: 'healthnutritionmonitoringapp.firebaseapp.com',
    storageBucket: 'healthnutritionmonitoringapp.firebasestorage.app',
    measurementId: 'G-2JWWTY40R2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy9q1_PI94DQI8l6eh52PUwCGI5q-az6M',
    appId: '1:198400828838:android:8aa9a1fcc0fda231995b67',
    messagingSenderId: '198400828838',
    projectId: 'healthnutritionmonitoringapp',
    storageBucket: 'healthnutritionmonitoringapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUSEiLZcRKsmYTVvGQ_6p72SA2CAKYGKI',
    appId: '1:198400828838:ios:c501cd3539b86e76995b67',
    messagingSenderId: '198400828838',
    projectId: 'healthnutritionmonitoringapp',
    storageBucket: 'healthnutritionmonitoringapp.firebasestorage.app',
    iosBundleId: 'com.example.myHealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUSEiLZcRKsmYTVvGQ_6p72SA2CAKYGKI',
    appId: '1:198400828838:ios:c501cd3539b86e76995b67',
    messagingSenderId: '198400828838',
    projectId: 'healthnutritionmonitoringapp',
    storageBucket: 'healthnutritionmonitoringapp.firebasestorage.app',
    iosBundleId: 'com.example.myHealthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD36ntBS4oSH5TsvhQHbPuv1ocCpjMaPSs',
    appId: '1:198400828838:web:9effccbfe0e7cf1c995b67',
    messagingSenderId: '198400828838',
    projectId: 'healthnutritionmonitoringapp',
    authDomain: 'healthnutritionmonitoringapp.firebaseapp.com',
    storageBucket: 'healthnutritionmonitoringapp.firebasestorage.app',
    measurementId: 'G-8GCH9PSCFG',
  );
}
